# Generated by Django 4.1.7 on 2023-03-14 08:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeTypeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem', models.CharField(max_length=32, verbose_name='事業所種別')),
            ],
            options={
                'verbose_name': '事業所種別',
                'verbose_name_plural': '事業所種別一覧',
            },
        ),
        migrations.CreateModel(
            name='SupportApproachSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem', models.CharField(max_length=32, verbose_name='支援・受講方法')),
            ],
            options={
                'verbose_name': '支援・受講方法',
                'verbose_name_plural': '支援・受講方法一覧',
            },
        ),
        migrations.CreateModel(
            name='SupportStatusSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem', models.CharField(max_length=32, verbose_name='支援状況')),
            ],
            options={
                'verbose_name': '支援状況',
                'verbose_name_plural': '支援状況一覧',
            },
        ),
        migrations.CreateModel(
            name='SupportThemeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem', models.CharField(max_length=32, verbose_name='支援テーマ')),
            ],
            options={
                'verbose_name': '支援テーマ',
                'verbose_name_plural': '支援テーマ一覧',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.CharField(help_text='介護保険事業所番号_介護サービス分類コード\u3000の半角文字列で構成されます。', max_length=32, verbose_name='識別子')),
                ('care_office_code', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='介護保険事業所番号')),
                ('name', models.CharField(max_length=64, verbose_name='事業所名')),
                ('care_service_code', models.CharField(max_length=16, verbose_name='介護サービス分類コード')),
                ('postal_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='事業所所在地')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='電話番号')),
                ('fax', models.CharField(blank=True, max_length=16, null=True, verbose_name='FAX番号')),
                ('town_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='事業所所在地の市区町村番号')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='経度')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='緯度')),
                ('company', models.CharField(blank=True, max_length=64, null=True, verbose_name='所属法人名')),
                ('owner', models.CharField(blank=True, max_length=32, null=True, verbose_name='経営者氏名')),
                ('manager', models.CharField(blank=True, max_length=32, null=True, verbose_name='責任者氏名')),
                ('capacity_of_guests', models.IntegerField(blank=True, null=True, verbose_name='定員')),
                ('url', models.CharField(blank=True, max_length=64, null=True, verbose_name='URL')),
                ('foundation_date', models.DateField(blank=True, null=True, verbose_name='設立年月日')),
                ('number_of_employees', models.IntegerField(blank=True, null=True, verbose_name='従業員人数')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.officetypeset', verbose_name='法人種別')),
            ],
            options={
                'verbose_name': '事業所',
                'verbose_name_plural': '事業所一覧',
            },
        ),
    ]
